### ISSUE TITLE
rewrite 'flags-to-memory.xsl'

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/dejump#25]
flags should be initialized before each `goto` (`while.`) objects:
```
seq
  flag.write -1
  flag.write ...
  while.
    or.
      ...
    [i]
      seq > @
        ...
```

**Comment by 0pdd** [comment]
@MikhailLipanin the puzzle [#33](https://github.com/objectionary/dejump/issues/33) is still not solved.

**Comment by 0pdd** [comment]
@MikhailLipanin the only puzzle [#33](https://github.com/objectionary/dejump/issues/33) is solved here.
