### ISSUE TITLE
flags-to-memory.xsl:9-10: Add template for objects before...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/dejump#33]
The puzzle `25-cede29ff` from #25 has to be resolved: 

https://github.com/objectionary/dejump/blob/85051b8fae87ab4830267547de1043f6230cc4c9/src/main/resources/org/eolang/dejump/flags-to-memory.xsl#L9-L10

The puzzle was created by Mikhail Lipanin on 07-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `25-cede29ff` has disappeared from the source code, that's why I closed this issue.

**Comment by MikhailLipanin** [comment]
@rultor hello

**Comment by MikhailLipanin** [comment]
@rultor release

**Comment by MikhailLipanin** [comment]
@yegor256  Can you add rultor to Collaborator-push settings in this repository?

**Comment by yegor256** [comment]
@MikhailLipanin done. Please, be careful with `release` command. The package will go to Maven Central and won't be removable from there, ever.
