### ISSUE TITLE
`master` branch

### ISSUE THREAD

**Issue by Graur** [objectionary/dejump#70]
Right now we cannot add some common checks because of the wrong branch name: `main`.
We need to create the `master` branch and make it default

**Comment by MikhailLipanin** [comment]
@Graur, I don't have access to settings for this repository to change default branch. If you have, can you do this?

**Comment by Graur** [comment]
@MikhailLipanin Me too. Can you create it?
And I think @yegor256 can help to make `master` branch to default one

**Comment by MikhailLipanin** [comment]
@Graur, sure, done.
@yegor256 Can you make `master` brunch as a default?

**Comment by yegor256** [comment]
@MikhailLipanin done. I also had to delete `master` that you created. Now, push from your local copy to master again, if you have something important over there.

**Comment by MikhailLipanin** [comment]
@yegor256 thanks!
