### ISSUE TITLE
pdd and xcop rules are absent 

### ISSUE THREAD

**Issue by Graur** [objectionary/dejump#71]
We need to add `pdd.yml` and `xcop.yml` to be sure a high quality checks are used in this repository

**Comment by MikhailLipanin** [comment]
@Graur, done

**Comment by Graur** [comment]
@MikhailLipanin I don't see any pull requests with this updates. Did you force push them to `master` branch?

**Comment by MikhailLipanin** [comment]
@Graur Yes, I forgot to do this via PR :( (f916ecddb36358be7810997e92efdc8c8d282ac4, 47eb5de181a6936e4f243468a87020507fd0031b)

**Comment by Graur** [comment]
@MikhailLipanin Please, use PR's in the next time.
Thanks!
