### ISSUE TITLE
no Maven release?

### ISSUE THREAD

**Issue by yegor256** [objectionary/dejump#88]
Still no Maven release? Let's do it.

**Comment by MikhailLipanin** [comment]
@rultor release, tag is 0.0.1

**Comment by MikhailLipanin** [comment]
@rultor release, tag=`0.0.1`

**Comment by MikhailLipanin** [comment]
@rultor release, tag=`0.0.1`

**Comment by MikhailLipanin** [comment]
@yegor256 [done](https://github.com/objectionary/dejump/releases/tag/0.0.1)

**Comment by yegor256** [comment]
@MikhailLipanin thanks!

**Comment by yegor256** [comment]
@MikhailLipanin please, add Maven badge to README, like we do it in other repos
